AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-sam

  Sample SAM Template for aws-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

    Tracing: Active
  Api:
    TracingEnabled: true
Resources:
  CommonDependencies:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: NpmLayer
      Description: NPM packages.
      ContentUri: layers/npm-layer/
  GetLocalWeatherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: weather/
      Handler: weather.getLocalWeather
      Runtime: nodejs18.x
      Layers:
        - !Ref CommonDependencies
      Architectures:
        - x86_64
      Events:
        GetLocalWeather:
          Type: Api
          Properties:
            Path: /weather
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - weather.ts
        External:
          - 'aws-sdk'
          - 'esbuild'
          - 'axios'
# Outputs:
#   # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
#   # Find out more about other implicit resources you can reference within SAM
#   # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#   HelloWorldApi:
#     Description: API Gateway endpoint URL for Prod stage for Hello World function
#     Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
#   HelloWorldFunction:
#     Description: Hello World Lambda Function ARN
#     Value: !GetAtt HelloWorldFunction.Arn
#   HelloWorldFunctionIamRole:
#     Description: Implicit IAM Role created for Hello World function
#     Value: !GetAtt HelloWorldFunctionRole.Arn
