AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-sam

  Sample SAM Template for aws-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

    Tracing: Active
  Api:
    TracingEnabled: true
Metadata: &esbuild_props
  Minify: true
  Target: es2020
  Sourcemap: true
  Packages: external
  # External:
  # - 'aws-sdk'
  # - 'esbuild'
  # - 'axios'
Resources:
  CommonDependencies:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: NpmLayer
      Description: NPM packages.
      ContentUri: src/layers/npm-layer/
  GetLocalWeatherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/weather/
      Handler: weather.getLocalWeather
      Runtime: nodejs18.x
      Layers:
        - !Ref CommonDependencies
      Architectures:
        - x86_64
      Events:
        GetLocalWeather:
          Type: Api
          Properties:
            Path: /weather
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        <<: *esbuild_props
        EntryPoints:
          - weather.ts
  GetCurrencies:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/currency/
      Handler: currency.getCurrencies
      Runtime: nodejs18.x
      Layers:
        - !Ref CommonDependencies
      Architectures:
        - x86_64
      Events:
        GetCurrencies:
          Type: Api
          Properties:
            Path: /currencies
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        <<: *esbuild_props
        EntryPoints:
          - currency.ts
